main: com.puddingkc.Mirrora.Mirrora
name: Mirrora
version: 1.1.1
api-version: "1.21"
author: PuddingKC
depend: [ "packetevents" ]

commands:
  mirror:
    description: Manage mirror regions.
    permission: mirrora.admin

permissions:
  mirrora.admin:
    default: op
