main: com.puddingkc.Mirrora.Mirrora
name: Mirrora
version: 1.2.1
api-version: "1.21"
author: PuddingKC
depend: [ "packetevents" ]
softdepend: [ "CraftEngine" ]

commands:
  mirror:
    description: Manage mirror regions.
    permission: mirrora.admin

permissions:
  mirrora.admin:
    default: op
  mirrora.autoCreate:
    default: op
